### ISSUE TITLE
egret3d 使用命令行创建项目报错

### ISSUE THREAD

**Issue by czy128518** [egret-labs/egret3d#18]
Error: Cannot find module 'args'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\caozhiyong.GT\AppData\Roaming\npm\node_modul
es\@egret\paper-cli\cli\cli.js:4:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by WanderWang** [comment]
收到，我们现在排查一下这个问题，您可以暂时尝试执行 npm install agrs -g 看下是否可以解决

**Comment by WanderWang** [comment]
问题已重现，我们会尽快修复这个问题

**Comment by WanderWang** [comment]
您可以暂时执行一次 ```npm install agrs -g ``` 绕过这个问题

**Comment by WanderWang** [comment]
问题已解决，您可以安装paper-cli 1.5.1 版本

**Comment by czy128518** [comment]
神速呀  我试试

**Comment by czy128518** [comment]
可以了  望egret技术大大提供些实例DEMO出来  谢谢
