### ISSUE TITLE
不能创建项目

### ISSUE THREAD

**Issue by jing334455** [egret-labs/egret3d#22]
我按照文档先安装了npm install @egret/paper-cli -g
然后执行这个paper create helloworld
然后就报错了，报错如下，我下载的是最新的版本
C:\Users\Administrator\AppData\Roaming\npm\node_modules\@egret\paper-cli\out\ind
ex.js:138880
        let {protocol} = url.parse(uri);
            ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modul
es\@egret\paper-cli\cli\cli.js:5:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

求助，还没开始就卡在这啦。。。

**Comment by WanderWang** [comment]
请使用最新版本的Node JS，我们后续版本里会加上node版本检测机制

**Comment by WanderWang** [comment]
最新的1.5.5 版本已经添加了对NodeJS版本的判断，最低版本 NodeJS 8.0
